services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped